version: '3.7'
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    command: mysqld --default-authentication-plugin=mysql_native_password --sort_buffer_size=1073741824
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - default
      - crypto-network
    restart: always

volumes:
  mysql:
    external: true

networks:
  crypto-network:
    external: true
